### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by aragorn67** [RamanLab/co-FSEOF#1]
I have 2 questions in the FSEOF.m code

What is the point of     steps = randperm(10); when the output is the same with     steps = linspace(1,10,10);

What is the point of comparing all the flux distrutions with (abs(FluxMatrix (RxnIndex, 1)) < abs(FluxMatrix (RxnIndex, 3)) && abs(FluxMatrix (RxnIndex, 4)) <...
                abs(FluxMatrix (RxnIndex, 6)) && abs(FluxMatrix (RxnIndex, 7)) < abs(FluxMatrix (RxnIndex, 9)))

Where the ouput is the same if comparing (abs(FluxMatrix (RxnIndex, 9)) > abs(FluxMatrix (RxnIndex, 1)))

**Comment by Lav22** [comment]
@aragorn67 
Hi!
Thanks for your interest in our algorithm! 
You can use both steps = randperm(10); or steps = linspace(1,10,10); We were initially facing some solver-related infeasibility issues. This was later figured out to be because of fixing both bound to the same value (now we use a short interval). randperm was used to figure out if the order of steps is causing any issues but that was not the case. We retained that code since it doesn't affect the output anyway.

We have made multiple comparisons so that we filter out reactions that have oscillating changes in fluxes (comparing only the end values can also include these in the output). This code ensures that the reaction targets obtained show an increase throughout.

Hope this helps. Let us know if you have further questions.
